FROM thecodingmachine/php:8.1-v4-apache-node16

# Set environment varibles
ENV TEMPLATE_PHP_INI production
ENV APACHE_DOCUMENT_ROOT /var/www/html/public
ENV PHP_EXTENSION_PDO_SQLITE 1

ADD --chown=docker:docker . /var/www/html
