version: "3.7"

services:
  webserver:
    image: 'thecodingmachine/php:8.1-v4-apache-node16'
    container_name: 'distilled-server'
    working_dir: /var/www/html/
    ports:
      - '80:80'
    extra_hosts:
      - "localhost:172.17.0.1"
    volumes:
      - ../:/var/www/html/
    environment:
      APPLICATION_ENV: development
      TEMPLATE_PHP_INI: production
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      PHP_EXTENSION_PDO_SQLITE: 1
